# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 13:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parties', '0002_guest_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='birth_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
