language: python
python:
  - "3.4"
services:
  - postgresql
addons:
  postgresql: "9.4"
cache:
  directories:
    - /home/travis/virtualenv
install:
  - pip install -r requirements.txt
script:
  - python manage.py test --settings=parties.settings -v2
